### ISSUE TITLE
Simplify "match all" use case?

### ISSUE THREAD

**Issue by tri-adam** [sylabs/oci-tools#93]
In the process of porting code over to use the new `(*OCIFileImage).Image` func, it's become clear to me that a common use case is to expect a single image within the `OCIFileImage`, and throw an error if exactly one image is not found in the root manifest.

In theory, `(*OCIFileImage).Image` (and `(*OCIFileImage).Index`) are very useful for this, and you can replace a lot of code by using a `match.Matcher` that selects all manifests from the root manifest, and then checks that exactly one image/index is found.

In practice, the `match` package doesn't define a "match all" function, so the user either needs to define this themselves, or inline it (ex. `func(v1.Descriptor) bool { return true }`). This works, but feels a bit repetitive.

I'm wondering if we should make this easier to solve via:

- Exporting a "match all" `match.Matcher` in `cci-tools`, or
- Allowing the user to pass a `nil` value for `match.Matcher`, and documenting this to mean "match all".

I sort of lean towards the latter, since `nil` currently causes a `panic` in GGCR, and this would prune off some paths towards that `panic`. And a `nil` matcher meaning "match all" seems somewhat intuitive. Curious if anyone else has thoughts here...

**Comment by dtrudg** [comment]
As discussed... a `nil` meaning "match all" sounds good to me.
